FROM ubuntu:18.04

MAINTAINER Umesh

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app

ENTRYPOINT [ "python" ]
docker run -d -p 5000:5000 flask-tutorial


CMD [ "app.py" ]
